### ISSUE TITLE
Missing documantion about makeThunkAsyncActionCreator 

### ISSUE THREAD

**Issue by ofermusaiwork** [welldone-software/redux-toolbelt#51]
Add documantions like in here
https://medium.com/welldone-software/redux-toolbelt-supercharge-your-redux-ec16e704fe93

and make sure to mention that we have to use 
import thunk from 'redux-thunk';
and add it to the middleware for using makeThunkAsyncActionCreator

**Comment by vzaidman** [comment]
fixed
